version: "2"
services:
    www:
        build: .
        ports:
            - "80:80"
        volumes:
            - .:/var/www/html/
        links:
            - db
        networks:
            - default
    db:
        image: mysql:5.6
        ports:
            - "3306:3306"
        environment:
            MYSQL_USER: guest
            MYSQL_PASSWORD: guest
            MYSQL_ROOT_PASSWORD: root
        volumes:
            - ./dump:/docker-entrypoint-initdb.d
            -  persistent:/var/lib/mysql
        networks:
            - default
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        links:
            - db:db
        ports:
            - 8080:80
        environment:
            MYSQL_DATABASE: progress
            MYSQL_USER: root
            MYSQL_PASSWORD: root
            MYSQL_ROOT_PASSWORD: root
        networks:
          - default
volumes:
  persistent: